### ISSUE TITLE
Device imports with Group Tag only, not Name; then with Name only, not Group Tag

### ISSUE THREAD

**Issue by SmithingJon** [OSDeploy/AutopilotOOBE#1]
This is the code I am using to configure and start autopilotOOBE.: 

Write-Host 'Installing Prerequisites...'
Install-PackageProvider -Name NuGet -Force
Write-Host 'Installing AutopilotOOBE'
Install-Module AutopilotOOBE -Force
Write-Host 'Configuring Parameters'
$Params = @{
    Title = 'TNU ITS Autopilot Registration'
    GroupTag = 'FSA'
    GroupTagOptions = 'FSA','ITS','SHARED','TWS','PROD'
    Hidden = 'AddToGroup','AssignedUser'
    PostAction = 'Restart'
    Assign = $true
    Run = 'NetworkingWireless'
    Docs = 'https://autopilotoobe.osdeploy.com/'
}
AutopilotOOBE @Params

Any device I run the script on will import correctly; but only with the Group Tag filled in in Autopilot Devices in Endpoint Manager. Checking back 20 minutes the group tag is now empty and that the computer name is now filled out. The Profile is unassigned.

**Comment by OSDeploy** [comment]
I think you may have some Dynamic assignments going on and I don't think it's AutopilotOOBE doing this as it is merely passing parameters to Get-WindowsAutopilotInfo. Can you run a test without AutopilotOOBE and just use Get-WindowsAutopilotInfo?

![image](https://user-images.githubusercontent.com/12970006/128042428-ef7a5780-cde4-4143-aeae-ecadb93331f3.png)

**Comment by SmithingJon** [comment]
I did testing with Just Get-WindowsAutopilotInfo and I believe it was giving me the same issue. What I ended up doing was writing my own code to change names after the device Assigns a profile.
